services:
  - type: web
    name: blog-api-assignment
    env: python
    buildCommand: |
      pip install -r requirements.txt
    startCommand: |
      python manage.py migrate && python manage.py collectstatic --noinput && daphne blog_project.asgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: blog_project.settings
