services:
  - type: web
    name: blog-api-assignment
    env: docker
    plan: free
    dockerContext: .
    dockerfilePath: Dockerfile
    buildCommand: |
      python manage.py collectstatic --noinput
    startCommand: >
      gunicorn blog_project.wsgi:application --bind 0.0.0.0:8000
